### ISSUE TITLE
I want to get SIM2MNIST.

### ISSUE THREAD

**Issue by Dong1P** [daniilidis-group/polar-transformer-networks#1]
Hello. I read the paper well.
I am interested in your paper.I want to train with different data once.
so  Will you be able to get a SIM2MNIST dataset?

Thank you!!

**Comment by machc** [comment]
Hello, thanks for your interest. You can download SIM2MNIST [here](https://drive.google.com/file/d/1AtVj4xqdshyYEOMU7EwvrVjcZkgBDZCL/view?usp=sharing). I'll add the release of functions to load/train with it  to my to do list. For now you may have to tweak the data loading and architecture a bit.

**Comment by Dong1P** [comment]
Thank you for your data.

I am trying to reconstruct your code once without data augmentation.
I do not get the STN Rotation result as I have mentioned in the article.
Do you have any additional things?
The network used the same size as it appeared in the paper.
Could you upload the MNIST RTS Dataset?

Thank you!!

**Comment by machc** [comment]
Sorry for the delayed response. Please find MNIST RTS [here](https://drive.google.com/file/d/1CTFmnbxdEkvvwm7298VxPQbvRw2AZLry/view?usp=sharing). 

The results we present for the Spatial Transformer Networks are with modified localization network (the architectures suggested in the original STN paper did not perform well). Please check Appendix A in our paper for architecture details.

**Comment by tarokiritani** [comment]
@machc Could you release the code that generates SIM2MNIST? I am thinking of making a slightly modified version of it. Thanks!

**Comment by machc** [comment]
Hi @tarokiritani,

Please check the code below which I took from my notes (I have not tested; it may need a few tweaks). 

```python
import pickle
# load mnist from tensorflow tutorials
from tensorflow.examples.tutorials.mnist import input_data


def get_random_img(X):
    return X[np.random.choice(len(X))]


def random_rot_scale(im, scale_range=(1, 2.4), rot_range=(0., 360.), resize_after_rot=True):
    rot = rot_range[0] + np.random.rand()*(rot_range[1] - rot_range[0])
    im = skimage.transform.rotate(im,
                                  rot,
                                  preserve_range=True,
                                  resize=resize_after_rot,
                                  mode='constant')
    sc = scale_range[0] + np.random.rand()*(scale_range[1] - scale_range[0])
    shape = [int(sc*s) for s in im.shape]
    im = skimage.transform.resize(im, shape, preserve_range=True, order=1,
                                  mode='constant')

    return im


def copy_random_patch(im, size=(8, 8)):
    r, c = im.shape
    i, j = np.random.randint(0, r-size[0]), np.random.randint(0, c-size[1])
    return im[i:i+size[0], j:j+size[1]].copy()


def paste_random_patch(im, patch, pos=None):
    r, c = im.shape
    size = patch.shape
    if pos is None:
        i, j = np.random.randint(0, r-size[0]), np.random.randint(0, c-size[1])
    else:
        i, j = pos

    im[i:i+size[0], j:j+size[1]] += patch
    im[im > 1] = 1

    return i, j

mnist = input_data.read_data_sets('/tmp/tf-mnist', one_hot=True)

# we swap train and test datasets to have more challenging task
# with 10k train and 50k test samples
dset_orig = {'x_train': mnist.test.images.reshape(-1, 28, 28),
             'y_train': mnist.test.labels,
             'x_test': mnist.train.images.reshape(-1, 28, 28),
             'y_test': mnist.train.labels,
             'x_validation' : mnist.validation.images.reshape(-1, 28, 28),
             'y_validation': mnist.validation.labels}

X = dset_orig['x_train']
NCLUTTER = 8
DIM = (96, 96)

dset = {}
for k, v in dset_orig.items():
    if 'x' in k:
        dset[k] = np.zeros((len(v), DIM[0], DIM[1]))
    else:
        dset[k] = v

for k, v in dset_orig.items():
    if 'x' in k:
        for im1, im2 in zip(v, dset[k]):
            digit = random_rot_scale(im1)
            paste_random_patch(im2, digit)
            for _ in range(NCLUTTER):
                patch = copy_random_patch(get_random_img(X))
                paste_random_patch(im2, patch)

# save
np.savez_compressed(os.path.expanduser('~/bigdata/mnist_cluttered_scale_rotated.npz'), **dset)

```

**Comment by tarokiritani** [comment]
@machc Thanks a lot! I just realized that the training dataset contains 55k images, instead of 50k as described in your paper.

**Comment by freepoet** [comment]
Hi,@machc .
I can't open the [link](https://drive.google.com/file/d/1CTFmnbxdEkvvwm7298VxPQbvRw2AZLry/view?usp=sharing) you gave,
Can you provide a link for Chinese users to download?
Thankks!

**Comment by dinukadesilva** [comment]
@machc If possible, could you please upload or point me to the `Rotated MNIST`, and `MNIST R` datasets used in the paper? I like to replicate some results.
